spring:
  application:
   name: bank
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bank_schema
        format_sql: true
        hbm2ddl:
          create_namespaces: true
  liquibase:
    change-log: classpath:database/db.changelog-master.yml
    enabled: true
server:
 port: 8082
 servlet:
   context-path: /my-bank
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    version: openapi-3-1

